Add code tests
Summary:
Adds support for light weight code tests where we can assert on the parts of the byte code we care about.  Uses a script which validates the generated code.  The script can contain:

"# Comment line"
"..." wild card to match opcodes until the next opcode matches
OPNAME OPARG   - matches an opname and oparg exactly
OPNAME * - matches an opname
* OPARG - matches an oparg

The oparg currently supports strings, lists, and frozensets, tuples, and None as well as basic block ids in the format <block:id>.

Test cases are checked in as .py files, and the test is run against the basic block graph, so the opargs aren't resolved to ints yet, so they're relatively stable to things like messing w/ co_consts.

One sample test is added and there are test cases to test the test infrastructure.

Test Plan:
python3 -m test_compiler

If a test fails, you can get one of several asserts:

AssertionError: False is not true : mismatch, expected XX YY, got LOAD_CONST None

AssertionError: Extra bytecodes not expected

Trailing script elements: [('opname, oparg'), ...]